kube-bind/kube-bind

.goreleaser.yaml
Then the versioned downloads work for krew.
=> goreleaser: publish releases

.github/workflows/ci-docs-only.yaml, README.md
Until we are in the real index.
=> README: add krew index to instructions

contrib/example-backend/http/handler.go, pkg/kubectl/bind/plugin/authenticate.go, pkg/kubectl/bind/plugin/bind.go
Like https://mangodb.de/authorize?c=4Mm8Vd&p=52295&s=4cgpcy.
=> Short authz URL

pkg/kubectl/bind-apiservice/plugin/konnector.go
=> kubectl-bind: properly format konnector wait

pkg/kubectl/bind-apiservice/cmd/cmd.go, pkg/kubectl/bind/cmd/cmd.go
Fixing https://twitter.com/JamesMunnelly/status/1585957861359726592.
=> *: enable client-go auth plugins

pkg/kubectl/bind-apiservice/plugin/konnector.go, pkg/kubectl/bind/plugin/bind.go
=> kubectl-bind: little indention fixes

README.md, deploy/examples/crd-mangodb.yaml
This PR adds example crd to be easily applied during local environment setup.
=> Add more descriptive sample crd apply step

deploy/examples/crd-mangodb.yaml
Signed-off-by: Pulak Kanti Bhowmick <pulak@appscode.com>
Fix #142
=> Add status sub resource in MangoDB crd

README.md
This was my personal favorite of KubeCon NA 2022 talks and I think it deserves a spot in the readme.
=> Add KubeCon talk as reference to readme

pkg/kubectl/bind-apiservice/plugin/konnector.go
Signed-off-by: Pulak Kanti Bhowmick <pulak@appscode.com>
Fix #144 
Only check for konnector current version when user using official/default image.
=> Fix konnector image override bug for custom image

contrib/example-backend/controllers/clusterbinding/clusterbinding_reconcile.go
Signed-off-by: Pulak Kanti Bhowmick <pulak@appscode.com>
=> Fix ClusterRoleBinding is not found bug while deleting it

pkg/kubectl/bind/plugin/bind.go, pkg/kubectl/bind/plugin/flags.go
=> Add konnector-image flag for top bind command

contrib/example-backend/http/handler.go
=> Use base64.URLEncoding for URL

test/e2e/bind/happy-case_test.go
This PR improves a type in the e2e tests in response to [this suggestion](https://github.com/kube-bind/kube-bind/pull/175#discussion_r1329284992).
=> Use ResourceScope from apiextensions-apiserver instead in e2e tests

guides/local-setup-with-kind.md
I've found myself jumping through some hoops to get kube-bind running all locally on my laptop the past few days.
So, hoping it will be helpful to others I've written up the steps as a small guide.
Step 3 in the "Setup" section is a bit of a pain point, I'm happy about any suggestions how to avoid specifying the host IP there.
=> Add guide for a local kube-bind setup using kind

.github/workflows/ci.yaml, .github/workflows/goreleaser.yml, .github/workflows/image.yaml, .ko.yaml, Dockerfile, go.mod
=> 👾  bump golang 1.23

.github/workflows/image.yaml
Followup for https://github.com/kube-bind/kube-bind/pull/215
=> Pin signer verison 

guides/local-setup-with-kind.md
The guide now shows setup where all components are in-cluster.
=> doc: updated "local-setup-with-kind" user guide

OWNERS
Fixes #
```release-note
Add  @mjudeikis as approvers
```
=> :book: add mjudeikis to approvers

docs/content/developers/konnector/controllers/cluster/.pages, docs/content/developers/konnector/controllers/cluster/apiserviceexport.md
This will add missing apiserviceexport controller docs to the work of Daniel, https://github.com/kube-bind/kube-bind/pull/243
=> 📖 Add apiserviceexport controller docs

.github/pull_request_template.md
Fixes #
```release-note
NONE
```
=> Allign kube-bind PR template with kcp

cli/pkg/crd2apiresourceschema/plugin/crd2apiresourceschema.go
Add conversion flag to `CRD2APIResourceSchema` that allows passing CRDs from file.
/kind feature
Fixes #
```release-note
NONE
```
=> Add CRD to APIResourceSchema conversion from file

backend/config.go, backend/provider/provider.go, go.mod, go.sum
Revert MCR bump. Runner interface is yet not working. 
/kind bug
Fixes #
```release-note
Revert multicluster-runtime bump
```
=> Revert runner. Its broken. (#331)
