kube-bind/kube-bind

.github/workflows/ci.yaml, .github/workflows/image.yaml
In Makefile we build with ldflags. These extra builds are harmful for both cost and time.
=> .github/workflows: avoid multiple builds and save cost

pkg/kubectl/bind-apiservice/plugin/konnector.go
To fix:
```
Newer konnector v0.0.16 installed. To downgrade to v0.0.16 use --downgrade-konnector.
```
=> konnector: avoid 'newer' version message when equal

pkg/konnector/controllers/cluster/servicebinding/servicebinding_controller.go, pkg/konnector/controllers/cluster/servicebinding/servicebinding_reconcile.go, pkg/kubectl/bind-apiservice/plugin/servicebindingrequest.go
We left the loop early and did not return any binding to print.
=> kubectl-bind: fix request loop when pre-existing

.ko.yaml
To get the right version string in the konnector image, hopefully.
=> .ko.yaml: set ldflags for the right packages

.github/workflows/goreleaser.yml, .github/workflows/image.yaml, cmd/konnector/cmd/konnector.go, contrib/example-backend/http/handler.go, contrib/example-backend/server.go, pkg/konnector/controllers/cluster/serviceexport/serviceexport_reconcile.go
In namespaced scope of the backend, only show namespaced CRDs on the resources page.
=> example-backend: only show CRDs of the right scope

contrib/example-backend/http/server.go, contrib/example-backend/options/serve.go, contrib/manifests/example-backend/insecure/example-backend.yaml, contrib/manifests/example-backend/letsencrypt/example-backend.yaml
This introduces `--listen-address` which is more idiomatic and can include a port as well.
This is a preparation for new command line options for the cache implementation.
cc @sttts
=> contrib/example-backend: remove listen-ip/listen-port in favor of listen-address

cmd/kubectl-bind/main.go, pkg/kubectl/bind/plugin/bind.go
The random number generator is not being properly initialized. This makes the sessionID on oauth workflow not be properly randomized, and make it easier to intercept/impersonate it.
=> Seed rng for random oauth sessionid

pkg/kubectl/bind/plugin/bind.go, test/e2e/bind/happy-case_test.go, test/e2e/framework/bind.go
ResourcePrinter supports adding yaml separator automatically. Only requirement is using the same ResourcePrinter object for all resources.
This PR removes the hacky solution and makes changes to better align with standard kubectl commands.
=> Use BindOptions-wide resource printer

pkg/konnector/controllers/cluster/cluster_controller.go, pkg/konnector/controllers/cluster/servicebinding/servicebinding_controller.go, pkg/konnector/controllers/cluster/servicebinding/servicebinding_reconcile.go, pkg/konnector/konnector_controller.go, pkg/konnector/konnector_reconcile.go
Signed-off-by: Pulak Kanti Bhowmick <pulak@appscode.com>
Fix #140 
As konnector is running APIServiceBinding controller for each provider cluster, so each controller should skip others provider's APIServiceBinding object.
=> Fix servicebinding controller reconciler bug

contrib/example-backend/kubernetes/manager.go
Here's the panic I got:
```
2022/12/02 13:18:44 http: panic serving 127.0.0.1:53118: runtime error: invalid memory address or nil pointer dereference
goroutine 2404 [running]:
net/http.(*conn).serve.func1()
/home/linuxbrew/.linuxbrew/Cellar/go/1.19.3/libexec/src/net/http/server.go:1850 +0xbf
panic({0x1c4fb80, 0x32f16f0})
/home/linuxbrew/.linuxbrew/Cellar/go/1.19.3/libexec/src/runtime/panic.go:890 +0x262
github.com/kube-bind/kube-bind/contrib/example-backend/kubernetes.(*Manager).HandleResources(0xc0002e7380, {0x2254240, 0xc00093ff50}, {0xc00064b3e0, 0x23}, {0xc000a88cdc, 0x8}, {0xc000a88ceb, 0xb})
/home/nick/src/kube-bind/contrib/example-backend/kubernetes/manager.go:124 +0x3ee
github.com/kube-bind/kube-bind/contrib/example-backend/http.(*handler).handleBind(0xc000181760, {0x2252f08, …
```
=> fix a panic in the example backend

pkg/konnector/controllers/servicebinding/servicebinding_controller.go
The event handler on the consumer secrets informer (in the konnector's APIServiceBinding controller) was registered twice, this PR removes the second (unneeded) occurrence.
See the lines right above the removed ones to verify that the event handler is already registered.
=> Remove duplicate event handler from informer

pkg/konnector/controllers/servicebinding/servicebinding_controller.go, pkg/konnector/konnector_controller.go
Remove the unused CRD lister and indexer from the konnector's APIServiceBinding controller that reconciles kubeconfig secrets. They had been added by mistake and aren't needed.
This change was agreed upon [here](https://github.com/kube-bind/kube-bind/pull/149#issuecomment-1410870035).
=> Remove unused CRD lister and indexer from konnector's controller

deploy/crd/bootstrap.go
Fix the message of the error returned when a decoded object that's expected to be a CRD isn't a CRD (in the code that installs the CRDs in the K8s cluster).
The message printed the wrong got type, this PR makes it print the right got type.
=> Fix error message: print correct got type

GOVERNANCE.md, OWNERS, SECURITY.md
This PR adds a GOVERNANCE.md file inspired by CNCF's Project Governance template https://github.com/carolynvs/cncf-project-template/blob/79bce741b54f33f1e81a313b0b077e2dd79c0096/GOVERNANCE-maintainer.md.
=> Bootstrap governance

cmd/example-backend/main.go, contrib/example-backend/controllers/clusterbinding/clusterbinding_reconcile.go, contrib/example-backend/deploy/01-clusterrole.yaml, pkg/konnector/controllers/cluster/serviceexport/serviceexport_reconcile.go, pkg/kubectl/bind-apiservice/cmd/cmd.go, pkg/kubectl/bind/cmd/cmd.go
This PR tries to improve on two things.
1. The access to apiservicenamespaces seems to be defined twice.
```
👉 Downloads $ kubectl get clusterrole kube-binder -oyaml | tail -n 24
- apiGroups:
- kube-bind.io
resources:
- apiservicenamespaces
verbs:
- create
- delete
- patch
- update
- get
- list
- watch
- apiGroups:
- kube-bind.io
resources:
- apiservicenamespaces
verbs:
- create
- delete
- patch
- update
- get
- list
- watch
```
This PR tries to fix it by cleaning up the bootstrapping manifest.
2. Some typo fixes.
=> Fixes to the 'kube-binder' clusterrole

pkg/konnector/controllers/cluster/serviceexport/status/status_controller.go
This PR introduces two fixes to the status controller. I arrange the them as two separate commits for easier review.
The first commit fixes `enqueueConsumer` of the status controller, for namespaced objects.
To check the corresponding APIServiceNamespace, we need
- its namespace which should be the 'cluster namespace' shown in the [Technical Overview](https://github.com/kube-bind/kube-bind#technical-overview). Or in other words, the `c.providerNamespace` in the code;
- its name which is the same as the namespace that holds the incoming object in the consumer cluster.
From other places of the code, looks like 'upstream' is used to refer to the provider and 'downstream' to the consumer. So I also renamed the variable `upstreamKey`. Please correct me if I am wrong.
The second commit fixes …
=> Fix enqueue functions of the status controller

pkg/konnector/controllers/cluster/cluster_controller.go, pkg/konnector/controllers/cluster/namespacedeletion/namespacedeletion_controller.go
The key lacked the provider namespace.
=> konnector/namespacedeletion: correctly map local namespace to APIServiceNamespace

pkg/konnector/controllers/cluster/servicebinding/servicebinding_reconcile.go, pkg/konnector/controllers/cluster/servicebinding/servicebinding_reconcile_test.go
Before this change, the reconciler would check the new CRD to see if it had the correct owner reference. But the new CRD always has the correct ownership reference!
After this change, the reconciler checks if the existing CRD to see if it has the correct owner reference, which seems like the intended behavior.
=> servicebinding: fix a bug in ownership check

pkg/konnector/controllers/cluster/serviceexport/status/status_controller.go
If an incoming object's corresponding APIServiceNamespace doesn't live in the expected cluster namespace, the status controller should skip enqueuing the key for the incoming object --- as described in the `logger.V(3)` info.
But seems that the code is not doing the skipping. This PR tries to make the skipping happen.
=> Make the skip happen when there is 'consumer mismatch' in status controller

README.md
This PR updates the README, primarily in the intro, to address #177 and #178 .  This PR also adds a note to the technical overview picture, explaining what part of the system is doing each of the actions between clusters.
=> Revise intro in README for visual, logic issues

contrib/example-backend/deploy/01-clusterrole.yaml, pkg/konnector/controllers/cluster/serviceexport/cluster-scoped/utils.go, pkg/konnector/controllers/cluster/serviceexport/cluster-scoped/utils_test.go, pkg/konnector/controllers/cluster/serviceexport/multinsinformer/informer.go, pkg/konnector/controllers/cluster/serviceexport/serviceexport_reconcile.go, pkg/konnector/controllers/cluster/serviceexport/spec/spec_controller.go, pkg/konnector/controllers/cluster/serviceexport/spec/spec_reconcile.go, pkg/konnector/controllers/cluster/serviceexport/status/status_controller.go, pkg/konnector/controllers/cluster/serviceexport/status/status_reconcile.go, test/e2e/bind/fixtures/provider/crd-foo.yaml, test/e2e/bind/happy-case_test.go
This PR tries to do two things regarding cluster-scoped APIs.
1. Completely enable the exporting and syncing of cluster-scoped APIs. As mentioned by @sttts in the [slack channel](https://kubernetes.slack.com/archives/C046PRXNJ4W/p1689088717859549?thread_ts=1688665656.221059&cid=C046PRXNJ4W), the exporting of cluster-scoped APIs is almost working. Some small tweaks are added in 934bda0 to make it complete.
2. Resolve the name conflicts for cluster-scoped API objects. Most work of the PR is for this second thing. To do that, a shim is implemented to a) translate between consumer side object names and provider side object names, b) filter object names for individual consumers. I came up with a diagram to make it easier to be reviewed. The shim is represented by the black curve in the middle …
=> Add supports to cluster-scoped APIs

pkg/apis/kubebind/v1alpha1/helpers/serviceexport.go, pkg/apis/kubebind/v1alpha1/helpers/serviceexport_test.go
Fixes a bug where a ServiceExport would not contain a storage version for CRDs that use webhook conversion, but where the first version is not the storage version.
fixes #168
=> Fix: Storage version for webhook conversion CRDs

contrib/example-backend/controllers/serviceexportrequest/serviceexportrequest_controller.go, contrib/example-backend/controllers/serviceexportrequest/serviceexportrequest_reconcile.go, contrib/example-backend/options/options.go, contrib/example-backend/server.go, deploy/crd/kube-bind.io_apiserviceexports.yaml, pkg/apis/kubebind/v1alpha1/apiserviceexport_types.go
This PR begins to better address the isolation of the cluster-scoped service objects. As a [follow up](https://github.com/kube-bind/kube-bind/pull/175#issuecomment-1721074910) to a previous PR.
This PR
- adds a `ClusterScopedIsolation` field to the spec of `APIServiceExport`;
- exposes this field as a flag of the example-backend;
- initializes this field when the "kube-bind-example-backend-serviceexportrequest" controller creates an APIServiceExport object.
This PR hasn't added other controllers' reactions to this field, yet.
=> Add ClusterScopedIsolation to APIServiceExportSpec

.github/workflows/goreleaser.yml
Update `cytopia/upload-artifact-retry-action` to **v0.1.7,** this should be using `actions/download-artifact: v3`.
Yes `actions/download-artifact: v3` is also being deprecated, but using v4 with `cytopia/upload-artifact-retry-action` would require a change there first. I'm hoping this helps at least for now.
=> update upload-artifact-retry-action to v0.1.7

.github/workflows/goreleaser.yml
Update `gorleaser.yml` versions based on what is working in kcp project. Uses the same actions, but version numbers are newer.
=> fix: workflow goreleaser, update versions for actions

.github/workflows/goreleaser.yml, .github/workflows/image.yaml
We dont need them in the end. We need tags for the go module, but not for artefacts. Was a mistake adding them.
=> Remove triggers

.github/workflows/image.yaml
Use the latest signing keys
2.7.0 we use is from Jun 3, 2023
=> Use latest cosign in CI

pkg/kubectl/bind/plugin/authenticate.go, pkg/kubectl/bind/plugin/bind.go, pkg/kubectl/bind/plugin/flags.go
Allows skip TLS verification when running in TLS mode with self-signed certificates:
```
kubectl bind https://127.0.0.1:6443/export --insecure-skip-tls-verify      
```
=> Add skip-insecure for calling exports via cli

guides/local-setup-with-kind.md
This PR adds a comment on how to install kubectl-bind plugin.
=> guide: add a comment on how to install kubectl-bind plugin

cli/cmd/kubectl-bind/cmd/kubectlBind.go, cli/cmd/kubectl-bind/cmd/kubectlBind_test.go, cli/pkg/kubectl/bind/cmd/cmd.go
This aims to fix the order of commands in `kubectl` plugin, that is currently displayed like this:
```bash
./bin/kubectl-bind  
kube-bind is a project that aims to provide better support for service providers and consumers that reside in distinct Kubernetes clusters.
For more information, see: https://kube-bind.io
Usage:
bind [command]
Available Commands:
bind        Bind different remote types into the current cluster.
completion  Generate the autocompletion script for the specified shell
help        Help about any command
```
The current order shows bind bind subcommand.
```bash
./bin/kubectl-bind bind 
DISCLAIMER: This is a prototype. It will change in incompatible ways at any time.
Bind different remote types into the current cluster.
Usage:
bind bind [flags]
bind bind [command]
``` …
=> fix: restore bind as the root cmd in cli

docs/content/.pages, docs/content/developers/.pages, docs/content/developers/backend/.pages, docs/content/developers/backend/http/.pages, docs/content/developers/backend/http/api-binding.md, docs/content/developers/backend/http/cluster-binding.md, docs/content/developers/backend/index.md, docs/content/developers/index.md, docs/content/developers/konnector/.pages, docs/content/developers/konnector/controllers/.pages, docs/content/developers/konnector/controllers/apiservicebinding.md, docs/content/developers/konnector/controllers/cluster/.pages, docs/content/developers/konnector/controllers/cluster/apiservicebinding.md, docs/content/developers/konnector/controllers/cluster/apiservicenamespace.md, docs/content/developers/konnector/controllers/cluster/clusterbinding.md, docs/content/developers/konnector/controllers/konnector.md, docs/content/developers/konnector/index.md, docs/mkdocs.yml, docs/requirements.txt
The purpose of this PR is to add some initial developer documentation to provide insight into how the konnector works and how a kube-bind client interacts with the provider backend. At the moment, the pages mainly contain diagrams that show
* the interaction between a kube-bind client and the provider backend during cluster and API binding
* the set of controllers implemented in the konnector
I tried to describe the interaction between a kube-bind client and the provider backend in a general way - e.g. some actions like installing the konnector, which is currently implemented in the kubectl plugin, are not shown in the diagrams. Also, not all of the konnector controllers are documented yet.
Overall I would love to hear your feedback, if this is something that adds value to the kube-bind …
=> 📖 docs: add initial developer documentation

.golangci.yaml, Makefile, contrib/example-backend/server.go, pkg/indexers/serviceexportrequest.go, pkg/konnector/controllers/cluster/servicebinding/servicebinding_controller.go, test/e2e/framework/kcp.go
Migrating golangci-lint to v2, fixing all the lint issues
Fixes https://github.com/kube-bind/kube-bind/issues/259
```release-note
NONE
```
=> 🌱 update golangci-lint to v2

kcp/bootstrap/server.go
There is no battery with an empty name in kcp and IMHO this is misleading to use a map with a pseudo element, instead of just an empty map.
/kind cleanup
Fixes #287
```release-note
NONE
```
=> WIP - remove "" battery from kcp bootraping
